### ISSUE TITLE
Don´t work in docker

### ISSUE THREAD

**Issue by aruznieto** [synzen/Discord.RSS-Clone#12]
When I install it, the web give me an error 502

**Comment by synzen** [comment]
Please provide the steps of what you did, otherwise I cannot reproduce your issue. Otherwise,

1. Add the token env var to both bot and web services in `docker-compose.yml`
2. Set up the rest of web service env vars
3. `docker-compose up`

**Comment by aruznieto** [comment]
I modify docker-compose.yml as you can see in this image (https://imgur.com/a/Q4Mwi2a)

- DRSS_BOT_TOKEN = DRSSWEB_BOT_TOKEN
- DRSSWEB_BOT_CLIENTID and DRSSWEB_BOT_CLIENTSECRET (https://imgur.com/atUX5n5)

The rest of parameters are like you write as you can see in the 1st image

**Comment by synzen** [comment]
And how are you accessing the site?

**Comment by aruznieto** [comment]
I have a reverse proxy, so I´m accessing with a subdomain. For example, rss.domain.com, automatically the proxy "redirect" me to the port 8081

**Comment by synzen** [comment]
If you reach the site at local_ip:8081 within your network (where local_ip is the ip of the host machine), you should be able to access the site. Anything more than that, such as reverse proxies, you'll have to maintain and debug on your own since that is out of the scope of what is necessary to get the web working.
