### ISSUE TITLE
Issue regarding image preview

### ISSUE THREAD

**Issue by EPFLRQN** [synzen/Discord.RSS-Clone#5]
![image](https://user-images.githubusercontent.com/45467260/82831376-dc132700-9eea-11ea-9d72-28fb4c604007.png)

**Comment by EPFLRQN** [comment]
The links appear but the image preview doesn't

**Comment by synzen** [comment]
Given that you did not disable image previews in `rss.options` and you did not put `<` and `>` around your links, this is not a problem with the bot. Discord treats all text the same, whether it comes from a user or a bot.

If you post the exact same URL yourself in the same channel, you will get the same result with no embed. This is either because of your own user settings for Link Preview:
![image](https://user-images.githubusercontent.com/18688793/82836275-4056cc00-9e94-11ea-82d7-1ebc21faccc1.png)


Or because you disabled server-wide or channel-specific Embed Links permission:
![image](https://user-images.githubusercontent.com/18688793/82836351-5a90aa00-9e94-11ea-8478-7a4786ff3493.png)
